# Generated by Django 3.1 on 2020-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
