# Generated by Django 3.1 on 2020-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_to_remove'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('to_remove', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('individual', 'Физическое лицо'), ('entity', 'Юридическое лицо')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['title'],
            },
        ),
    ]
