# Generated by Django 3.1 on 2020-09-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_storage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='StorageItem',
        ),
    ]
