# Generated by Django 3.1 on 2020-09-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200928_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', unique=True, verbose_name='Товар'),
        ),
    ]
