# Generated by Django 3.1 on 2020-10-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200929_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageitem',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
