# Generated by Django 3.1 on 2020-10-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201001_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в документе',
                'verbose_name_plural': 'Довары в документе',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('to_remove', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('destination_type', models.CharField(choices=[('receipt', 'Приход'), ('expense', 'Расход')], max_length=7, verbose_name='Тип документа')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-dt_created'],
            },
        ),
    ]
