# Generated by Django 3.1 on 2020-10-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_document_documentitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentitem',
            options={'verbose_name': 'Товар в документе', 'verbose_name_plural': 'Товары в документе'},
        ),
    ]
