# Generated by Django 3.1 on 2020-10-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201001_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apply_flag',
            field=models.BooleanField(default=False, verbose_name='Документ проведен'),
        ),
    ]
